### ISSUE TITLE
sh: cfn- commands not found

### ISSUE THREAD

**Issue by mmell** [bazaarvoice/cloudformation-ruby-dsl#46]
After updating the cloudformation-ruby-dsl gem to ~> 0.5.0 the cfn-*-stack commands are not found. 

It started working again after `brew install aws-cfn-tools`.

**Comment by temujin9** [comment]
If by "not found" you mean they are no longer available in your default path, this is intentional. The `service` binary was interfering with the native Linux `service` command.

If by "not found" you mean that invocations of cloudformation-ruby-dsl scripts fail, then we've got a bug. In that case, get me the results of `echo $PATH` and `sudo find / -xdev -executable -type f -name cfn-cmd`.

**Comment by mmell** [comment]
An invocation of cloudformation-ruby-dsl to (for example) `expand` still works. My reading of [this line in "Removing vendored binaries"](https://github.com/bazaarvoice/cloudformation-ruby-dsl/commit/d65b020239982cce5fb62c07771c39ea823f7008#diff-fdc133b99327fd40129c898b7cdf8395R29) was that the binaries were supposed to still be available, but they are not. I have no cfn-cmd unless I `brew install aws-cfn-tools`.

**Comment by temujin9** [comment]
They are still physically present (in [the vendor folder](https://github.com/bazaarvoice/cloudformation-ruby-dsl/tree/master/vendor/AWSCloudFormation-1.0.12/bin)), but the gem no longer inserts them into your $PATH. You can always do so manually, by modifying your PATH. However, the `brew` command you suggested is probably a cleaner approach.
