### ISSUE TITLE
cfn-delete-stack was not ported over to the new aws-cli version

### ISSUE THREAD

**Issue by jdrago999** [bazaarvoice/cloudformation-ruby-dsl#51]
Is this on the todo list or was it excluded on purpose?

**Comment by jonaf** [comment]
Hi, this was not intentionally excluded. We didn't know if people were actually using it this way. Since previously, we were just shelling out to `cfn-cmd`, you could execute your template using any of the commands that `cfn-cmd` would take, even if we hadn't implemented it. Now that we're using the AWS Ruby SDK, however, we have to specifically enumerate and implement whatever commands we want to implement.

@temujin9 Any opinions on going back and supporting *all* of the `cfn-cmd` commands? It'd be pretty easy to do.

**Comment by temujin9** [comment]
It's an oversight on my part, I believe. Fixing it now.

Cheers,

Nathaniel Eliot

Hi, this was not intentionally excluded. We didn't know if people were
actually using it this way. Since previously, we were just shelling out to
cfn-cmd, you could execute your template using any of the commands that
cfn-cmd would take, even if we hadn't implemented it. Now that we're using
the AWS Ruby SDK, however, we have to specifically enumerate and implement
whatever commands we want to implement.

@temujin9 <https://github.com/temujin9> Any opinions on going back and
supporting *all* of the cfn-cmd commands? It'd be pretty easy to do.

—
Reply to this email directly or view it on GitHub
<https://github.com/bazaarvoice/cloudformation-ruby-dsl/issues/51#issuecomment-114658901>
.

**Comment by temujin9** [comment]
@jonaf Ah, I see what you mean. Yes, we should support all commands, unless it's unfeasible.

**Comment by jonaf** [comment]
Totally feasible. The `cfn-cmd` ones just passed "whatever" you did to `cfn-cmd`, which could result in obscure errors if you type the command incorrectly. Now, however, we have to actually implement each facet of the API we intend to support. However, it doesn't look like the usage ever purported that "any" command could be used, so I only implemented those API features that were expressly named in the usage.

**Comment by temujin9** [comment]
I think all the [cfn-commands](https://github.com/bazaarvoice/cloudformation-ruby-dsl/tree/ccdc802b515d480254e42d5ef18925de3140e7ce/vendor/AWSCloudFormation-1.0.12/bin) which pertain to a single stack should be supported, in some fashion. So "delete" and "cancel-update", and maybe a "describe" that rolls up the various "cfn-describe-*" calls into one coherently presented report.

I think we can skip the "cfn-list-*" calls, but I could be persuaded that they have value here, as well.

Everything else that we no longer support should also probably be explicitly caught and flagged as "already been deprecated", so there's no confusion on the end-user part. I doubt it will matter much, but I'd like the transition to be clean / obvious as possible. I'll get you a PR for that, momentarily.

**Comment by jdrago999** [comment]
Thank you!  I've rolled back to v0.5.4 for now, but can't wait to get onto the new aws-cli version.

**Comment by temujin9** [comment]
@jonaf #52 addresses the deprecation flagging part of this.
